### ISSUE TITLE
CuratorFramework and IntegrationTest Exceptions

### ISSUE THREAD

**Issue by kpm1985** [apache/fluo#1000]
This is a place for me to document the work I've begun on addressing the errors output to the console during the run of mvn verify. For the moment I will have to be brief but I did a fair amount of investigation. I'll say more later.

I have a branch that has a tiny sleep modification to oracle server and it kills a lot of the errors by checking state. I'd appreciate if someone could check this out. I will transfer mailing list discussion here asap.

 https://github.com/kpm1985/fluo/tree/CuratorErrors

**Comment by kpm1985** [comment]
I've pushed and reset a few times on this branch, this has been good experience to expand and learn a little more about git.

Anyways, with these modest changes, the only errors that are appearing during mvn verify are in Thrift or something I don't have forked/cloned. The first change sleeps on the state of the curator framework, the second sleeps on isLeader. Basically Fluo gets a chill pill and waits for things to finish and for some reason this has the effect of disappearing the error messages. 

I'm doing further reading and getting to learn more about ZooKeeper and Curator so I can do a better job at this but this is a first analysis. 

https://github.com/kpm1985/fluo/tree/CuratorErrors

**Comment by mikewalch** [comment]
It would be awesome to reduce some of our random test failures.  It looks like you are the right track as I bet most of the failures are timing related.   However, the code you are working is definitely tricky. We need to make sure there is no adverse effects with adding sleeps/delays.

**Comment by kpm1985** [comment]
@keith-turner Recommended looking at CuratorFramework.blockUntilConnected which I just finished trying out and it works also. This is the change to the OracleServer.takeLeadership method before the call to getData that is fluently styled right after. 

I've dropped changes to the other method that was throwing exceptions, OracleServer.getTimestampImpl until I understand it better.

**Comment by kpm1985** [comment]
@mikewalch @keith-turner @ctubbsii 

There are a few issues I've identified that are legitimate concerns. For the sake of this please attention to synchronization.

      synchronized (this) {
        byte[] d = curatorFramework.getData().forPath(maxTsPath);
        currentTs = maxTs = LongUtil.fromByteArray(d);
      }

Notice the synchronization on these objects from takeLeadership() : non synchronized method with a synchronized block

  private synchronized long getTimestampsImpl(String id, int num) throws TException {

Consider this method, it is synchronized. 

        allocateTimestamp();

This line is not synchronized. Follow code into this method:

    long newMax = Long.parseLong(new String(d)) + 1000;


    curatorFramework.setData().withVersion(stat.getVersion()).forPath(maxTsPath,
        LongUtil.toByteArray(newMax));
    maxTs = newMax;

Notice there is no synchronization on these. Object monitors and locks to do not inherit. This is made clear at this line: 

    // do this outside of sync
    stampsHistogram.update(num);

I've profiled the code over the last week, this is a race condition that is leading to a lot of non-deterministic build errors and failures.

**Comment by kpm1985** [comment]
Ok so its been too long since I've looked at this. I just pulled down the new code and ran mvn with some errors left. 

I want to finish this up soon because eliminating these errors to a reasonable degree could help clear the waters when other errors are thrown.

Should I try to upgrade curator and see how that works or keep working on this patch with refactoring etc or both?

**Comment by ctubbsii** [comment]
Probably both. I think an updated curator would be reasonable, but it may not fix the problem.

**Comment by kpm1985** [comment]
Ok I will try a clean upgrade and then apply my logic to a patch if
necessary. Thank you Christopher.

**Comment by kpm1985** [comment]
Hello guys, following back up on this I have successfully used Curator 2.12
which has a lot of bugs fixed.

I think it sounds reasonable to upgrade to this version as it was as simple
as editing the pom. No new errors are created.

However, as feared, it does not fix the issue. But it does upgrade and fix
a lot of bugs in the dependency.

**Comment by ctubbsii** [comment]
Probably worth upgrading anyway.

**Comment by kpm1985** [comment]
Fixed by #1035
