### ISSUE TITLE
Create integration test for `FluoAdmin.remove()`

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#1002]
There is a discussion about this on #999

https://github.com/apache/fluo/pull/999#discussion_r161251692

**Comment by kpm1985** [comment]
I just read this and noticed someone mentioned oserver.start().

If the Oracle server is started and takes leadership immediately, a race
condition can occur on isLeader and the state of the curator framework (not
the one from shared resources).

Beware. I've been investigating with flight recorder and some other dumping
tools.

**Comment by kpm1985** [comment]
@keith-turner I followed the discussion above and would like to try this issue. I've noticed a few preliminary things and have a few questions:

There is no check to see if the oracle is running for FluoAdminImpl.remove(), when I did some preliminary fooling around I noticed that. 

Going by your test outline in #999 this test would write some table data, call remove, and read the table make sure it was actually cleared. I was thinking of writing to the table using a mutation and batch writer and then call remove and create a scanner and verify the entries are cleared. Am I in the right direction? I am still familiarizing myself with Accumulo.

Thank you!

**Comment by keith-turner** [comment]
> I was thinking of writing to the table using a mutation and batch writer and then call remove and create a scanner and verify the entries are cleared. Am I in the right direction?

For that test I was thinking of reading and writing data using Fluo's API.   Only using the Accumulo API for the test would ensure the table was cleared, however it would not ensure that zookeeper was cleared.

**Comment by keith-turner** [comment]
Closed by 1cc9276e454505b82d15f72ef7be1c3008606d43
