### ISSUE TITLE
Refactor remove and init apis to check if running

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#1003]
The fluo commands for init and remove check if an application is running.  However the API calls for init and remove do not do these checks.  These checks should be removed from the command and into the API calls.  There is a discussion about this on #999

**Comment by keith-turner** [comment]
https://github.com/apache/fluo/pull/999#discussion_r161250500

**Comment by jkosh44** [comment]
Is @alanblueshift working on this? If not I'd like to take this issue.
