### ISSUE TITLE
SyncCommitObserver should throw an exception if multiple methods called.

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#1011]
If more than one method is called on [SyncObserver](https://github.com/apache/fluo/blob/master/modules/core/src/main/java/org/apache/fluo/core/async/SyncCommitObserver.java), then any method after the first should throw an IllegalStateException.

**Comment by keith-turner** [comment]
The goal of this issue is to throw an exception if any of the methods `committed()`, `failed()`, `alreadyAcknowledged()`, or `commitFailed()` is called more than once.  Below are two possible ways to accomplish this.

# Use synchronized
 * Make all methods synchronized
 * Drop all volatile, not needed with sync
 * Drop CountDownLatch and replace with Object wait and notify methods (can do this since methods are sync)
 * Add a boolean that tracks if one of the 4 methods was called.  For each method check the boolean and throw exception if set.  If not set, then set it.

# Use AtomicBoolean
 * Add an AtomicBoolean that tracks if one of 4 methods were called
 * When a method is called, is compared and set on atomic boolean to change from false to true. If compare and set fails, it means something else called method so throw exception.

For either method, Guava's `Preconditions.checkState()` method can be used.

I posted this on helpwanted.

https://helpwanted.apache.org/task.html?a3862f6ea243e0003cb0992beb127c57598f80ef

**Comment by asr21** [comment]
hi keith I have submitted a PR. Please check if it looks correct. This is my first time contributing to any project. So I may have made small mistakes :)

**Comment by keith-turner** [comment]
Welcome @asr21 !  There are some comments on the PR #1013, let me know if you have any questions.
