### ISSUE TITLE
Add option to scan command for showing notifications

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#1026]
Currently the only way to see outstanding notifications is by doing `fluo scan -a myApp --raw -c ntfy`.  However this shows deleted notifications.  It would be very useful to have the ability to only see active notifications.  Could add an option to the scan command for this.

**Comment by alanblueshift** [comment]
How about `fluo scan -a myApp --tail`? I'm facing some debugs scenarios in development that a tail would help a lot.

**Comment by keith-turner** [comment]
@alanblueshift for `--tail` scan has an option to start at a row, does this help?

**Comment by alanblueshift** [comment]
Yes! Actually I was thinking about to use this resource to implement a tail like scan. That stays connect until a CTRL+C from user.
