### ISSUE TITLE
Update lib/ahz/pom.xml for Accumulo 2 and Hadoop 3

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#1063]
This is follow on work for #1062

**Comment by ctubbsii** [comment]
Follow on work to do what, exactly? Please add more descriptive summaries of the work to be done, so that somebody else could do it if you don't, and so somebody reading this issue will have some insight into what the issue is, without having to read all the previous changes from the linked issue.

**Comment by keith-turner** [comment]
Need to make the pom get the correct Hadoop 3 and Accumulo 2 dependencies.  One major diff with hadoop 3 is the new client-api and client-runtime jars.

**Comment by keith-turner** [comment]
The current pom file works, I tested it yesterday.  I think this issue was fixed by 549d645addb330f4ae2e074447428cb86b5a9a3f
