### ISSUE TITLE
Research a standard Java style eclipse formatter for Fluo

### ISSUE THREAD

**Issue by mikewalch** [apache/fluo#163]
Currently, Fluo uses the Accumulo style format for Eclipse.  This uses 160 chars for max line but we would like to use 100 chars for Fluo.  We either need to create our own style format xml (it can be checked into modules/contrib) or use Google's:

http://code.google.com/p/google-styleguide/source/browse/trunk/eclipse-java-google-style.xml

There may be an issue with different tab size if we move to Google style.

**Comment by kpm1985** [comment]
I think this 4 year old issue is handled because we have the code format file for eclipse now and we also use the impsort pluggin.
