### ISSUE TITLE
Investigate Mesos as an option for running Fluo

### ISSUE THREAD

**Issue by cjnolet** [apache/fluo#290]
Mesos is getting much traffic in the cloud community. In fact, there are many companies like Twitter, eBay and Netflix are using it in production at massive scale. Some customers may be abandoning YARN as their scheduling mechanism and trying to lean more towards fully Mesos. It also seems pretty easy to integrate with. It's definitely worth investigating what it would take to get Fluo running on it.

**Comment by keith-turner** [comment]
http://aurora.apache.org/

**Comment by mikewalch** [comment]
Closed by #883
