### ISSUE TITLE
Fluo must use same version of Guava as Twill

### ISSUE THREAD

**Issue by mikewalch** [apache/fluo#466]
This is due to Twill's use of Guava's `Service` interface in its API.  Twill has an outstanding issue to fix this in [TWILL-69](https://issues.apache.org/jira/browse/TWILL-69).  However, they may be a way to structure Fluo so that this conflict is avoided.  

This conflict is preventing Fluo from upgrading to a newer version of Guava.  Twill currently uses Guava 13.0.1 but Guava has released a 18.0 version.

**Comment by cjmctague** [comment]
Updating Twills version would allow us to bump Guava's version to `16.0.1` but we could not go any higher until Hadoop is updated to `2.7.2+` 
https://stackoverflow.com/a/36443787

**Comment by ctubbsii** [comment]
There's so many known vulnerabilities in previous versions of Hadoop (less than 2.7), that it probably makes sense to go ahead and bump all the way to 2.7.6 or later, which I think is still being maintained (looks like 2.7.7 was recently released).

**Comment by cjmctague** [comment]
Guava has been updated. Closed by e019c79dafa2769b9e0d48ba1923d84702447922
