### ISSUE TITLE
Upgrade to Accumulo 1.6.2 and fix failing ITs

### ISSUE THREAD

**Issue by mikewalch** [apache/fluo#474]
In #467, an upgrade to Accumulo 1.6.2 was attempted but it caused ITs (like the GarbageCollectionIteratorIT) to fail consistently.  This is probably due to a timing issue with the failing ITs and MiniAccumuloCluster.  This should be fixed before Fluo is upgraded to use 1.6.2.

**Comment by ctubbsii** [comment]
Adding explanation for closure for future selves: project has already moved to Accumulo 1.7 and 1.9, and ITs are passing.
