### ISSUE TITLE
Improve Oracle log message

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#786]
The following feedback is from @joshelser on this [mailing list thread](https://lists.apache.org/thread.html/f4fabfec7ce8c70f599691b249f0ef96a36c021e3c0e83c9f350d4cd@%3Cdev.fluo.apache.org%3E).

> - Nit: waitTotal and waitPeriod are not really.. informative. Does this mean it waited 1second this time and will wait 2seconds next time?
> 
> 2016-10-05 22:22:37,023 [oracle.OracleClient] WARN : Waiting for timestamp from Oracle. Is it running? waitTotal=1s waitPeriod=2s

**Comment by kpm1985** [comment]
I'd like to jump on this one, if that is cool @keith-turner This is line 371 from Oracle Client:
          log.warn("Waiting for timestamp from Oracle. Is it running? waitTotal={}s waitPeriod={}s",

First there is a check to see if the timeout is positive (do we want to accept a value of 1?)
      int timeout = env.getConfiguration().getConnectionRetryTimeout();
      if (timeout < 0) {

In this block, if there is no positive value for the timeout, the values are assigned and an exponential backoff of 2^x is used until we have waited 60 seconds and then we warn out again

      if (timeout < 0) {
        long waitPeriod = 1;
        long waitTotal = 0;
        while (!tr.cdl.await(waitPeriod, TimeUnit.SECONDS)) {
          checkClosed();
          waitTotal += waitPeriod;
          if (waitPeriod < MAX_ORACLE_WAIT_PERIOD) {
            waitPeriod *= 2;
          }
          log.warn("Waiting for timestamp from Oracle. Is it running? waitTotal={}s waitPeriod={}s",
              waitTotal, waitPeriod);

Now if there was a good positive value from the Config then we bypass the exponential back off and go here, wait one time, and complete. All of these are using count down latch functions to wait (just to show understanding of code).

      } else if (!tr.cdl.await(timeout, TimeUnit.MILLISECONDS)) {
        throw new FluoException("Timed out (after " + timeout
            + "ms) trying to retrieve timestamp from Oracle.  Is the Oracle running?");
      }

If that is correct, I can update the getStamp() documentation as a seperate issue if needed, and tackle this one. Thanks @keith-turner talk to you next week sometime!

**Comment by kpm1985** [comment]
To answer the posters question and give a clear explanation of the log message is as follows:

1) wait total corresponds to the total time waited for this stamp.
2) wait period corresponds to the amount of time to wait before we check the state of the count down latch again.

Note: the user is not made aware of the actual timeout value, just the total time they have waited and how long each wait interval is in between checking the latch

**Comment by mikewalch** [comment]
@kpm1985, nice break down of the code. Any updates to the documentation would be great but I think the issue was the log message.  

```
2016-10-05 22:22:37,023 [oracle.OracleClient] WARN : Waiting for timestamp from Oracle. Is it running? Client has a waited a total of 1s and will retry again in 2s
