### ISSUE TITLE
Make drip in Fluo dark logo a lighter color

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#815]
I thnik the drip in the Fluo dark logo is too dark.  It does not contrast well with dark backgrounds.   I recently updated Fluo's [logo for twitter][1] and I lightened the drip.   If the main dark logo is updated, need to circle back and make Twitter consistent.

[1]: https://twitter.com/apachefluo

**Comment by keith-turner** [comment]
The source for the fluo logo for dark backgrounds is here.

https://github.com/apache/fluo/blob/master/contrib/fluo-logo-dark.svg

**Comment by KrishAmal** [comment]
Hey @keith-turner  I would like to work on this  . How about a light blue color drip ?

**Comment by keith-turner** [comment]
Great @KrishAmal I look forward to your PR.  

> How about a light blue color drip ?

Yeah I think that is whats needed, not sure how light.  

If it helps, I think the SVG files were created using [Inkscape](https://inkscape.org/).

**Comment by KrishAmal** [comment]
Yes , Is this color okay ?
![image](https://user-images.githubusercontent.com/4433284/31055865-3cbcc4de-a6e7-11e7-8dd6-75afadff27ee.png )

**Comment by keith-turner** [comment]
@KrishAmal that looks good.  Have you tried against a dark background?  I think that will contrast well.

**Comment by KrishAmal** [comment]
@keith-turner yes , it looks fine . The change should be made only for the dark logo right ? 
![fluodark](https://user-images.githubusercontent.com/4433284/31109868-543fea8e-a820-11e7-897a-2c52d2919cb0.png)

**Comment by keith-turner** [comment]
@KrishAmal looks good.  Yeah, only need to change the dark logo.
