### ISSUE TITLE
Retrieve FluoConfiguration from Zookeeper using app name & connection.properties

### ISSUE THREAD

**Issue by mikewalch** [apache/fluo#846]
For #842, the API needs to be improved so that if a Fluo application was previously initialized, it's FluoConfiguration can be built by simply having connection.properties to Fluo instance and the application name.

**Comment by keith-turner** [comment]
Why does the configuration need to be retrieved from zookeeper?  What sequence of events will a user take with this functionality?

**Comment by mikewalch** [comment]
Closed by #883
