### ISSUE TITLE
Remove Thrift log spam when using Accumulo 2.0

### ISSUE THREAD

**Issue by mikewalch** [apache/fluo#885]
When Fluo is used with Accumulo 2.0, it uses Thrift 0.10 which spams the logs with a debug statement `Received <NUM>`.  Below are links to the Thrift issue and how Accumulo resolved it.

https://issues.apache.org/jira/browse/THRIFT-4062

https://issues.apache.org/jira/browse/ACCUMULO-4551

**Comment by ctubbsii** [comment]
Would be good to get more people to pressure Thrift on that issue to release a 0.10.1 with only this fix.

**Comment by kpm1985** [comment]
I added to the JIRA after you @ctubbsii to try and put some more social pressure on them.. alls I can say is is this normal to have such high demand and no appropriate response, the list was a lot longer than just us

**Comment by cjmctague** [comment]
[Thrift 0.11.0](https://lists.apache.org/thread.html/1c7da4292c8a89db3648cb14d8fb5342c316ac05e7dab644d6888815@%3Cdev.thrift.apache.org%3E) is up for the release voting. It includes the fix for this issue so we can get this handled in the next couple days, preferably before a 1.2.0 release

**Comment by keith-turner** [comment]
We have to be very careful with thrift versions.  Thrift has an IDL which is automatically translated to java code.  The automatically generated code uses libthrift.  Normally the code generated by thrift compiler X will only work with libthrift version X.   

The Accumulo client has code generated by the thrift compiler.  Given the constraints above, we often have to use the version of libthrift that Accumulo uses.

Ideally the thrift project would keep the libthrift API super stable such that code generated by thrift compiler version X would work with libthrift version Y if X<=Y.   However the project has made no attempt at this in the past.

**Comment by keith-turner** [comment]
For example Accumulo 1.7.X uses libthrift 0.9.1 and Accumulo 1.8.X uses libthrift 0.9.3.  If you try to use libthrift 0.9.1 with Accumulo 1.8.X it will break in strange ways.   

Luckily Fluo uses very little thrift functionality and the thrift code we automatically generate works with 0.9.1 and 0.9.3 at the moment.

It would be interesting to try Fluo and Accumulo with libthrift 0.11 and see if blows up.

**Comment by kpm1985** [comment]
https://issues.apache.org/jira/browse/THRIFT-4062 has been resolved. I am closing this issue.
