### ISSUE TITLE
Allow configuration to be passed to 'fluo oracle' & 'fluo worker' commands

### ISSUE THREAD

**Issue by mikewalch** [apache/fluo#914]
The `fluo oracle` and `fluo worker` should be able to support the following syntax to override the configuration read from `fluo-conn.properties`:

```
fluo oracle <app> -p key1=value1,key2=value2
fluo oracle myapp -p fluo.connection.zookepers=localhost/fluo,fluo.connection.zookeeper.secret=mysecret
```

**Comment by keith-turner** [comment]
Instead of comma separate could do multiple options like maven and java.  With maven and java can specify `-D` multiple times.
