### ISSUE TITLE
Ensure allocated timestamps are valid.

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#921]
Fluo uses the first three bits of the Accumulo timestamp for its own metadata.  Therefore when allocating timestamps its important to ensure that the first three bits are always zero.  A good place to do this check would be the [Stamp](https://github.com/apache/fluo/blob/master/modules/core/src/main/java/org/apache/fluo/core/oracle/Stamp.java) constructor.  The check should ensure that the passed in stamps are zero when anded with [ColumnConstants.PREFIX_MASK](https://github.com/apache/fluo/blob/master/modules/accumulo/src/main/java/org/apache/fluo/accumulo/util/ColumnConstants.java).  The check could be done using Guava preconditions.

**Comment by keith-turner** [comment]
I posted this on Apache's https://helpwanted.apache.org/.  Anyone coming from there and wishing to attempt this task, please feel free to ask any questions you have here.

**Comment by adepuravikrishna** [comment]
Hello Keith-turner, I would be interested in working on this issue. Is guava dependency added already to this project?

**Comment by keith-turner** [comment]
@adepuravikrishna yes, guava is already a dependency.

**Comment by adepuravikrishna** [comment]
Should it throw IllegalArgumentException when the a & b condition result is does not satisfy the 3 zeros condition?  and also should this check applies to both stamp, gcStamp variables?

**Comment by keith-turner** [comment]
> Should it throw IllegalArgumentException when the a & b condition result does not satisfy the 3 zero bits in the beginning condition?

yes, with a good error message.

> and also should this check applies to both stamp, gcStamp variables?

yes, the check should be done for both

**Comment by adepuravikrishna** [comment]
@keith-turner Thanks a lot for quick response. Currently I am running mvn package but having issues with building the project. Hopefully I can figure it out myself.

**Comment by keith-turner** [comment]
> Currently I am running mvn package but having issues with building the project. 

Feel free to post a link to your branch or share the error messages you are seeing from maven.

**Comment by adepuravikrishna** [comment]
@keith-turner Just created a pull request. Could you please review and comment the changes?
