### ISSUE TITLE
Inline Span static methods in Scanner builder

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#923]
To build a scanner over a row, something like the following needs to be done.

```java
 try (Snapshot snap = client.newSnapshot()) {
     CellScanner scanner =  snap.scanner().over(Span.prefix("d:")).build();
}
```

It would be nice to be able to do something like following instead.

```java
 try (Snapshot snap = client.newSnapshot()) {
     CellScanner scanner =  snap.scanner().overPrefix("d:").build();
 }
```

This fluent style would make writing code in an IDE with code completion more seamless.  To accomplish this I think the following methods should be added to [ScannerBuilder](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/api/src/main/java/org/apache/fluo/api/client/scanner/ScannerBuilder.java).  The implementations of these methods should call the existing static methods in [Span](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/api/src/main/java/org/apache/fluo/api/data/Span.java).

```java
interface ScannerBuilder {
  //implementations of following should call corresponding Span.exact() methods
  default ScannerBuilder over(Bytes row) {over(Span.exact(row));}
  default ScannerBuilder over(CharSequence row) {...}
  default ScannerBuilder over(Bytes row, Column col){...}
  default ScannerBuilder over(CharSequence row, , Column col){...}

  //implementations of following should call corresponding Span.prefix() methods
  default ScannerBuilder overPrefix(Bytes row) {over(Span.prefix(row));}
  default ScannerBuilder overPrefix(CharSequence row){...}
  default ScannerBuilder overPrefix(Bytes row, Column col){...}
  default ScannerBuilder overPrefix(CharSequence row, , Column col){...}
}
```

The java docs for the new methods should have a `@since` tag and link to the javadoc in the corresponding Span methods.

All existing test should be updated to use the new methods.  For example [ScannerIT](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/integration/src/test/java/org/apache/fluo/integration/impl/ScannerIT.java), FluoIT, WorkerIT, and WeakNotificationIT should be updated to use the new methods.

**Comment by codeandplay** [comment]
@keith-turner I can have a go on this issue, Thanks

**Comment by keith-turner** [comment]
Sounds good @codeandplay I look forward to your PR.  If you have any questions, feel free to ask here.

**Comment by keith-turner** [comment]
@codeandplay did you have any questions about this issue?

**Comment by kpm1985** [comment]
If this is up for grabs I'd like to take a shot, if not please keep me in mind for the next help wanted as it was very nice working with you.

**Comment by codeandplay** [comment]
Hi Keith,

Sorry for the delay of the fix, I have been held up with other work last
week. I will be probably the same for the this week and next. If @Kenneth
would like to take over, I am happy if he want to have a go. @Keith sorry
again about this.

**Comment by keith-turner** [comment]
Thanks @kpm1985 .  Looks like its open, if you want to give it a shot.

**Comment by kpm1985** [comment]
I will take it and thanks for letting me adopt this issue.

**Comment by AshishPB** [comment]
Is the issue taken or can I take it ?

**Comment by kpm1985** [comment]
I talked to Keith, if you want it, take it AshishPB.

**Comment by jevalen4868** [comment]
Hey folks, new guy here. Please let me know if this one is up for grabs.

**Comment by kpm1985** [comment]
@jeremy

I have vacated this issue but others have shown interest. Please file a
pull request with WIP to let everyone know your have claimed and are
working on this issue. I hope I have phrased this correctly.

**Comment by jkosh44** [comment]
I've seen this pass through a bunch of hands, so I'm gonna hop on line. If this frees up I'd like to give it a shot.

**Comment by jkosh44** [comment]
Don't mean to steal this from anyone. Just saying if it opens up again I'd like to work on it.

**Comment by keith-turner** [comment]
> Don't mean to steal this from anyone

I hope I didn't give that impression with my last post.  I didn't think you were attempting to do that.  I was just airing my thoughts based on activity I have seen on multiple issues posted to helpwanted.  I was not actually responding to anything in particular on this issue, until the last sentence.

> if it opens up again I'd like to work on it.

That is one thing I was trying to determine, is it open?

**Comment by jkosh44** [comment]
Gotcha, might as well give @AshB2108 some time to respond

**Comment by ctubbsii** [comment]
In my personal opinion, I think you can just start. You can always put a link to your personal branch, so others can collaborate with you on what will eventually be just a single pull request to the upstream Apache Fluo repository. Git being a distributed version control system is nice that way.

**Comment by ctubbsii** [comment]
As long as you've made a good faith effort to collaborate (including accepting feedback), nobody can fault you for "sniping" an particular bug, in my opinion.
