### ISSUE TITLE
Support direct comparisons between byte[] and Bytes

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#924]
When comparing byte[] and Bytes, this currently requires an allocation and a copy.  It would be nice to be able to do direct comparisons.   To avoid copy+allocation, could possibly add the following methods to [Bytes](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/api/src/main/java/org/apache/fluo/api/data/Bytes.java).   

```java
class Bytes {
   //note the method name contentEquals is used in String for types other than String
   public boolean contentEquals(byte[] bytes){...}
   public boolean contentEquals(byte[] bytes, int offset, int len){...}
   public int compareTo(byte[] bytes){...}
   public int compareTo(byte[] bytes, int offset, int len){...}
}
```

**Comment by keith-turner** [comment]
If interested in implementing this take a a look at [compareTo(Bytes)](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/api/src/main/java/org/apache/fluo/api/data/Bytes.java#L199) and [equals(Object)](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/api/src/main/java/org/apache/fluo/api/data/Bytes.java#L222).  Maybe all of these methods could be refactored to share code, not sure.  Also unit test will need to be added to [BytesTest](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/api/src/test/java/org/apache/fluo/api/data/BytesTest.java)

**Comment by adepuravikrishna** [comment]
@keith-turner  I would be interested in working on this issue.

**Comment by jkosh44** [comment]
Is this being worked on? I'd love to give it a shot.

**Comment by ctubbsii** [comment]
@jkosh44 It's all yours if you want it. Whatever implementation you come up with, I'll probably also roll in to apache/fluo-bytes#2

**Comment by jkosh44** [comment]
Hey I'm getting a 403 error when I try and push my code, any idea what's going on?

**Comment by ctubbsii** [comment]
@jkosh44 To where are you attempting to push your code? What is the URL of the git remote you are pushing to?

**Comment by jkosh44** [comment]
I was running "git push origin fluo-924" (the branch I created). my remote url is https://github.com/apache/fluo.git

**Comment by keith-turner** [comment]
@jkosh44 you need to fork the apache repo, push your changes to your fork, and then create a pull request.

https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/about-pull-requests/

**Comment by jkosh44** [comment]
Thanks, I missed that step. I made my fork, pushed my code, and a created pull request.
