### ISSUE TITLE
[fluo-parent] Formatter doesn't appear to format javadocs

### ISSUE THREAD

**Issue by ctubbsii** [apache/fluo#933]
Ran into revelc/formatter-maven-plugin#192 today using the new parent POM. Not sure what the problem is, but we may want to avoid using the new formatter until that's fixed. Might require going back to the old parent POM, or releasing a new one which reverts the formatter plugin version to what we were using before.

If javadocs aren't formatted, they can easily exceed the max line length and cause the build to fail due to checkstyle violations.

**Comment by kpm1985** [comment]
I've had all of my javadoc contribution formatted correctly with mvn compile. Specifically, when I failed a checkstyle and ran mvn compile it cleared my indentation issues. Running some tests with a stupid long javadoc string now.

**Comment by kpm1985** [comment]
Ok, I also found this out. If you do a stupid long line it breaks the revelc impsort plugin (that I love so much man, that is a flame war extinguisher I love it love it love it). 

Here is the branch, failing mvn install.  
https://github.com/kpm1985/fluo/tree/Javadoc-SuperLongLineTest

**Comment by ctubbsii** [comment]
@kpm1985 That's not broken because the line is long. It's broken, because it's not valid Java. There's no end tag to the Javadoc comment block. The impsort plugin fails, but so would the compiler plugin, or the formatter plugin, or findbugs, or checkstyle, or several others. impsort just runs early enough to have caught it first.

**Comment by kpm1985** [comment]
@ctubbsii Thanks, you caught the missing */, in haste I missed that. You're 100% correct the line length is not wrapping and is causing checkstyle fails. I am sorry for making such a stupid mistake, thanks for calling me out.

**Comment by ctubbsii** [comment]
Fixed with formatter-maven-plugin 2.7.0+
