### ISSUE TITLE
Make transaction info cache size configurable.

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#938]
Fluo caches information about failed transactions.  This helps speed up the case where multiple row/cols were modified by a failed transaction.  Currently this cache size is hard coded.  Also the timeout of the cache is hard coded.  It would be nice change these to impl properties.  Impl properties are ones that are not part of the public API and are tightly coupled to an internal implementation that could change at any moment.

The cache is created in the [ TxInfoCache constructor](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/core/src/main/java/org/apache/fluo/core/impl/TxInfoCache.java#L40).  In this constructor it would be nice to do something like :

```java
TxInfoCache(Environment env) {
   long cahceSize = FluoConfigurationImpl.getTxInfoCacheSize(env.getConfiguration());
   long timeOut = FluoConfigurationImpl.getTxInfoCacheTimeout(env.getConfiguration());
   //construct cache using vals above...not sure if should be long or int.. depends on type that cache takes
}
```

The methods above would have to be added to [FluoConfigurationImpl](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/core/src/main/java/org/apache/fluo/core/impl/FluoConfigurationImpl.java).  These methods should probably follow the pattern of `FluoConfigurationImpl.getTxCommitMemory()`

Possible property names are `fluo.impl.tx.failed.cache.size.mb` and `fluo.impl.tx.failed.cache.expireTime`

**Comment by kpm1985** [comment]
@keith I would like to take a crack at this one if possible simply due to the classes tight coupling with FluoConfiguration.

**Comment by keith-turner** [comment]
@kpm1985 that would be great if you could work on it

**Comment by kpm1985** [comment]
YES!!!

**Comment by kpm1985** [comment]
I am going to begin working on this immediately. Thank you for giving me
#938.
