### ISSUE TITLE
Make TransactorCache size configurable

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#939]
In Fluo, a Transactor is a process that executing transactions.  Each transactor has a  unique ID and registers itself in Zookeeper.  When a transaction reads data that another transaction has a lock on it needs to check in Zookeeper to see if the transactor executing the transaction is still alive.  Frequently checking in Zookeeper would be expensive, so this information is cached.  Currently the size of this cache is hard-coded.  This cache size should be configurable.  This changes in this issue would follow the same pattern as the changes for #938, except the [constructor for TransactorCache.java](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/core/src/main/java/org/apache/fluo/core/impl/TransactorCache.java#L49) would be modified.

Possible property names are `fluo.impl.tx.transactor.cache.size.entries` and `fluo.impl.tx.transactor.cache.expireTime`

**Comment by kpm1985** [comment]
I would like to tackle this issue is possible please.

**Comment by kpm1985** [comment]
Whoops, thought this was 938 sorry, please disregard.

**Comment by keith-turner** [comment]
The commit 650f044b7db16e732cfbf32f484f05ec34837df8 for #938 can be used as a template for this issue.

**Comment by kpm1985** [comment]
Would you like me to take this or work on something else @keith-turner ?

**Comment by kpm1985** [comment]
@keith-turner I'd like to do this one so I can finish up the *cache* classes please.

**Comment by keith-turner** [comment]
ok thanks @kpm1985
