### ISSUE TITLE
VisibilityCache constructor is out of date

### ISSUE THREAD

**Issue by kpm1985** [apache/fluo#942]
```java
  private final Cache<Bytes, ColumnVisibility> visCache;

  VisibilityCache() {
    visCache =
        CacheBuilder.newBuilder().expireAfterAccess(TxInfoCache.CACHE_TIMEOUT_MIN, TimeUnit.MINUTES)
            .maximumWeight(10000000).weigher(new VisWeigher()).concurrencyLevel(10).build();
  }
```
Needs to be changed to use the properties from FluoConfigurationImpl added today. In addition, I am adding a unit test that simply instantiates the class and makes sure its not null so this will be caught if a property is bogus in the future. I came across this just browsing my repo so this is kinda lucky, I think I erased TxInfoCache.CACHE_TIMEOUT_MIN with the earlier commit.

**Comment by kpm1985** [comment]
https://github.com/apache/fluo/pull/943

**Comment by keith-turner** [comment]
Good find, `TxInfoCache.CACHE_TIMEOUT_MIN` should be removed.  I think it would be good make this configurable with two new props.
