### ISSUE TITLE
Create a column buffer class for GarbageCollectionIterator

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#946]
Fluo has a [GarbageCollectionIterator][1] that cleans up bookkeeping info created by transactions that is no longer needed.  For this iterator to do its job, it must [buffer][2] a row/column in memory.  For this particular case, the row+column in each buffered key is always the same.  Therefore it would be more memory efficient to just buffer the timestamp and value.  The could be done by creating a new class like the following and modifying GarbageCollectionIterator to use it.

```java
/**
 * This class buffers Keys that all have the same row+column.  Internally 
 * it only stores one Key, a list of timestamps and a list of values.  At iteration 
 * time it materializes each Key+Value.
 */
class ColumnBuffer {
  /**
   * When empty, the first key added sets the row+column.  After this all keys
   * added must have the same row+column.
   */
  public void add(Key k, Value v);
  /**
   * Clears the dest ColumnBuffer and inserts all entries in destwhere the timestamp passes 
   * the timestampTest.
   */
  public void copyTo(ColumnBuffer dest, LongPredicate timestampTest);
  void clear();
  int size();
  Key getKey(int pos);
  Value getValue(int pos);
}
```

It would be really nice to create a unit test for this new class.  

For comparing if two keys have the same row+column, Key has a special function that can be used `Key.equals(Key key, PartialKey pk)`.   PartialKey is an enum that specifies how deep the equals check should go.

[1]: https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/accumulo/src/main/java/org/apache/fluo/accumulo/iterators/GarbageCollectionIterator.java
[2]: https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/accumulo/src/main/java/org/apache/fluo/accumulo/iterators/GarbageCollectionIterator.java#L68

**Comment by keith-turner** [comment]
I posted this on [help wanted](https://helpwanted.apache.org/task.html?185671696519ce34ea685e825e7db910e1d2e78e).  Need to remember to close when done.

**Comment by jkosh44** [comment]
can I give this a shot?

**Comment by keith-turner** [comment]
> can I give this a shot?

Yeap.  Let me know if you have any questions of feel free to post a WIP PR for discussion.

**Comment by keith-turner** [comment]
@jkosh44  I updated the proposed methods for ColumnBuffer.  The reason I changed it is looking at how the GCIter uses `keysFiltered`.  I think these methods will better support the filtererKeys case.  Can hopefully replace the code at [GarbageCollectionIterator. line 277](https://github.com/apache/fluo/blob/rel/fluo-1.1.0-incubating/modules/accumulo/src/main/java/org/apache/fluo/accumulo/iterators/GarbageCollectionIterator.java#L277) with something like the following.

```java
//assume keys and keysFiltered are of type ColumnBuffer
keys.copyTo(keysFiltered, timestamp -> {
      long colType = timestamp & ColumnConstants.PREFIX_MASK;
      if (colType == ColumnConstants.TX_DONE_PREFIX) {
        return completeTxs.contains(timestamp & ColumnConstants.TIMESTAMP_MASK;
      } else {
        return true;
      }
}
```

Also I think the `getKey(int pos)` and `getValue(int pos)` methods can be used currently where `get()` is called on the `keysFiltered` List w/o the need to create the intermediate `KeyValue` object.

**Comment by keith-turner** [comment]
My thinking with the `copyTo()` method is that it avoid having to materialize the Keys when copying from `keys` to `keysFiltered`.  I proposed this after looking at the code and seeing that the filtering was done on timestamp only.  This works nicely with internal impl of ColumnBuffer that only keeps timestamps.

**Comment by jkosh44** [comment]
@keith-turner 
Where should this new class go, the same folder? same question for the unit tests.

**Comment by keith-turner** [comment]
@jkosh44 same folder is good.

**Comment by jkosh44** [comment]
Hey @keith-turner I pushed some code and added comments about things I wasn't sure about. Can you take a look at it and let me know if I'm headed in the right direction?

**Comment by jkosh44** [comment]
Hey @keith-turner, I just want to make sure I understand the GarbageCollectionIterator class correctly. Is the idea to replace the keys and keysFiltered lists with ColumnBuffers?

**Comment by keith-turner** [comment]
> Is the idea to replace the keys and keysFiltered lists with ColumnBuffers?

That is correct @jkosh44
