### ISSUE TITLE
Support passing java options via enviroment variable

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#954]
In order to support apache/fluo-docker#2 it would be nice if the fluo scripts supported passing java options via environment variables.

**Comment by keith-turner** [comment]
I think one way to solve this issue is to support a `FLUO_JAVA_OPTS` env var.  Any java options set in this env var would be used by the fluo script when starting java processes.  This would allow `FLUO_JAVA_OPTS` to be set on the command line for docker, hopefully enabling a command like the following : 

```
docker run -d --network="host" -e FLUO_JAVA_OPTS=-Xmx4G fluo worker -a myapp -o fluo.connection.zookeepers=zkhost/fluo
```

Currently `fluo-env.sh` defines a `JAVA_OPTS` env var that is used by the `fluo` script.  Could modify `fluo-env.sh` to pre-pend `FLUO_JAVA_OPTS` to `JAVA_OPTS`.

**Comment by ctubbsii** [comment]
A slight variation on what @keith-turner said: you don't need to create a new property. You can just prepend the old value of `JAVA_OPTS` to the value set in the script, like what is commonly done with `CLASSPATH`, `PATH`, etc.

**Comment by srikailash** [comment]
I am interested to work on this issue . Currently setting up Fluo on my laptop.

**Comment by srikailash** [comment]
FLUO setup question : Hello , i have some issues with starting accumulo on my laptop . I have setup apache hadoop and zookeeper . ./bin/accumulo init says 0 name nodes even if i have name nodes and data nodes running . Does any one face the same issue ? Please direct me to some FLUO installation instructions for mac os . (I tried uno , but that doesn't seem to work in my case) . Thanks in advance .

**Comment by keith-turner** [comment]
@srikailash  if you are using Accumulo 1.8, checkout the following instructions.

https://github.com/apache/accumulo/blob/1.8/INSTALL.md

**Comment by kpm1985** [comment]
Uno is really cool

**Comment by srikailash** [comment]
@kpm1985  question about Uno : I was being prompted for password for hadoop installation , it's not my root password and neither an empty string . What to do in that case ?

**Comment by kpm1985** [comment]
I think it is in the file under conf directory in a conference file

**Comment by kpm1985** [comment]
Stupid auto complete. In a . conf file sorry. Can help better in an hour
sorry for short responses in class.

**Comment by keith-turner** [comment]
@srikailash  I suspect ssh is prompting for a password.  Hadoop scripts use ssh to start services like the datanodes.  Ensure you have passwordless ssh setup.
