### ISSUE TITLE
Fluo scripts copy jars into fluo software dir.

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo#957]
For some commands, the fluo script will copy jars from HDFS to the local machine.  Currently the fluo script copies jars into `$FLUO_HOME/lib/app/<app name>`.  This has at least two problems.  First, its possible that commands running concurrently for the same app could interfere with each other.  Second, it possible that the software directory is not writable. 

One possible fix is the following :
 * Setup `FLUO_TMP` env var in `fluo-env.sh`.  Could default to `/tmp`
 * In scripts copy jars into dir like `mktemp -d $FLUO_TMP/fluo-"$app"-XXXXXXXXX`
 * Execute command and after if finishes remove tmp dir

**Comment by keith-turner** [comment]
I think this task would consist of the following :
  * Add `FLUO_TMP` to [fluo-env.sh](https://github.com/apache/fluo/blob/9e87f477463602533d8611c9561484d41d135654/modules/distribution/src/main/config/fluo-env.sh)
  * Modify the [fluo script](https://github.com/apache/fluo/blob/9e87f477463602533d8611c9561484d41d135654/modules/distribution/src/main/scripts/fluo) to use `mktemp` and `FLUO_TMP` everywhere `FluoGetJars` is run.

For example the code [fluo line 230](https://github.com/apache/fluo/blob/9e87f477463602533d8611c9561484d41d135654/modules/distribution/src/main/scripts/fluo#L230) could be changed to the following :

```bash
    # create a temp dir to fetch application jars to
    app_lib=mktemp -d $FLUO_TMP/fluo-"$app"-XXXXXXXXX
    $JAVA org.apache.fluo.command.FluoGetJars -d "$app_lib" -a "$app"
    export CLASSPATH="$conf:$app_lib/*:$CLASSPATH"
    $JAVA org.apache.fluo.command.FluoExec "${@:2}"
    # remove the temp app lib dir
   rm -rf $app_lib
```

**Comment by keith-turner** [comment]
I posted this on helpwanted : https://helpwanted.apache.org/task.html?593d4c92b8bb1883de0ae0403646737a88d188a3

**Comment by mptap** [comment]
@keith-turner: Gonna take a crack at this

**Comment by ctubbsii** [comment]
There's a similar strategy for creating, and later cleaning up, a temporary directory in https://github.com/apache/fluo-website/blob/gh-pages/_scripts/git-hooks/post-commit#L37-L39

**Comment by keith-turner** [comment]
Great @mptap, let us know if you have any questions.   

@ctubbsii the trap command is neat, I didn't know about that.  I have never done signal handling bash.  I googled it, seems one may be able to use human readable signal codes like `ERR` and `INT` instead of numbers. I got a little lost w/ all the quoting in the trap command, I suspect its expanding the variable and still leaving it quoted after expanding.

I think using the trap command to schedule the deletion on process exit is the way to go.  I tried to redo my example from above using trap, not sure if its correct.

```bash
    app_lib=$(mktemp -d "$FLUO_TMP"/fluo-"$app"-XXXXXXXXX) || die "fatal: unable to allocate a temporary directory"
    # sechedule removal of app_lib tmp dir when process exits
    trap "rm -rf '""$app_lib""'" 0 HUP INT QUIT TERM
    $JAVA org.apache.fluo.command.FluoGetJars -d "$app_lib" -a "$app"
    export CLASSPATH="$conf:$app_lib/*:$CLASSPATH"
    $JAVA org.apache.fluo.command.FluoExec "${@:2}"
```

**Comment by ctubbsii** [comment]
signal 0 should also be `EXIT`

I think you can actually simplify the trap command's quoting a bit, but if you do, it will generate a warning in shellcheck, for being a common mistake (I don't recommend this, but it may help understand what's being quoted and why):
```bash
trap "rm -rf '$app_lib'" EXIT HUP INT QUIT TERM
```

**Comment by keith-turner** [comment]
To really test this script, will need to run Fluo locally. Running Fluo requires Hadoop, Accumulo, and Zookeeper be running and setting these up takes a lot of time.  We wrote [Uno](https://github.com/astralway/uno) to automate setting these up for local development.  Uno can be used to test these script changes.   The instructions below show how to use Uno to test the script changes.  

```bash
git clone https://github.com/astralway/uno.git
cd uno/
# Uncomment export FLUO_REPO and set it to your fluo source directory.  This 
# will cause uno fetch to build a snapshot version of fluo.  This soruce dir should 
# have your modifications to fluo script.
vim conf/uno.conf
# This will build Fluo and download Hadoop, Zookeeper, and Accumulo
./bin/uno fetch fluo
# This will configure Fluo, Hadoop, Zookeeper, and Accumulo and start them
./bin/uno setup fluo
# This will add Fluo, Hadoop, Zookeeper, and Accumulo to path in current shell
 eval "$(./bin/uno env)"
cp install/fluo-1.2.0-SNAPSHOT/conf/fluo-app.properties ./my-app.properties
# Uncomment fluo.observer.init.dir and set it to dir containing 
# fluo-tour-0.0.1-SNAPSHOT.jar.  Instructions later in this comment about
# how to get this jar.
vim my-app.properties # TODO describe what to edit
fluo init -a myapp -p ./my-app.properties
# run oracle process in background needed to exec transactions
fluo oracle -a myapp > oracle.log &
# This will download app jar from HDFS to tmp dir and execute it
fluo exec myapp ft.Increment id000
# Edit fluo script if not working as expected.  Changes will need to be copied
# back to fluo source dir once you get it working as expected.
vim install/fluo-1.2.0-SNAPSHOT/bin/fluo
fluo exec myapp ft.Increment id000
fluo exec myapp ft.Increment id002
fluo scan -a myapp
# Should see oracle running as first background job
jobs
# Kill oracle if its first background job
kill %1
# Kill Hadoop, Zookeeper, and Accumulo
./bin/uno kill
```
Make sure to take a look at the Uno requirements section.  Uno requires password less ssh and JAVA_HOME to be set.  Make sure that `ssh localhost env | grep JAVA_HOME` works and does not ask for a password.

The instructions above require a simple Fluo app for the exec command to execute.   I created [fluo-tour.zip](https://github.com/apache/fluo/files/1422443/fluo-tour.zip) containing a simple app and attached it.  To build this yourself, take the following java code.

```java
package ft;
import javax.inject.Inject;

public class Increment {
  
  @Inject
  private static FluoConfiguration fluoConfig;
  
  private static Column SUM_COL = new Column("stat","sum");
  
  public static void main(String[] args) {
    try(FluoClient client = FluoFactory.newClient(fluoConfig)) {
      try(Transaction tx = client.newTransaction()) {
        int currSum = Integer.parseInt(tx.gets(args[0], SUM_COL,"0"));
        int newSum = currSum+1;
        tx.set(args[0], SUM_COL, newSum+"");
        tx.commit();
        System.out.println("Set sum to "+newSum);
      }
    }
  }
}
```

And do the following to quickly build a jar.

```bash
git clone -b fluo-tour https://gitbox.apache.org/repos/asf/fluo-website fluo-tour
cd fluo-tour/
# copy Increment.java to src/main/java/ft
mvn package
# jar will be in target dir
```

**Comment by mptap** [comment]
@keith-turner: Verified hadoop/yarn files are created in `/tmp`. PR: https://github.com/apache/fluo/pull/964
